dist: trusty
language: python
python: "2.7"
notifications:
  email: false

branches:
  only:
  - master
  - ansible-3

env:
  matrix:
    - USE_ENV=stage
    - USE_ENV=prod

before_install:
  - sudo apt-get -y update

install:
  - pip install ansible
  - pip install ansible-lint
  - wget https://releases.hashicorp.com/terraform/0.11.2/terraform_0.11.2_linux_amd64.zip
  - wget https://github.com/wata727/tflint/releases/download/v0.5.4/tflint_linux_amd64.zip
  - wget https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip
  - find . -name '*.zip' 2>/dev/null | xargs -n 1 sudo unzip -o -d /usr/local/bin
  - touch ~/.ssh/appuser.pub && touch ~/.ssh/appuser 
  - WORKDIR=$(pwd)

script:
  - packer validate -var-file=packer/variables.json.example packer/db.json
  - packer validate -var-file=packer/variables.json.example packer/app.json
  - ansible-lint ./ansible/playbooks/site.yml
  - cd terraform/${USE_ENV}
  - terraform init; terraform validate --var-file=terraform.tfvars.example; tflint --var-file=terraform.tfvars.example --error-with-issues
